language: node_js
services:
  - postgresql
node_js:
  - 5
addons:
  postgresql: 9.4
before_script:
  - psql -c 'create database monsieur_test;' -U postgres
script:
  - npm run lint
  - npm run test-ci
cache:
  directories:
    - node_modules